// crates/BuiltinAudioPlugins/crates/equz8/editor/src/components/Knob.tsx
import {
  useCallback,
  useEffect,
  useId,
  useRef,
  useState,
  type PointerEvent as ReactPointerEvent,
} from 'react'
import { clamp } from '../lib/eq'
import { snapKnobDial } from '../lib/motion'

const ANGLE_START = 135
const ANGLE_SWEEP = 270
const DRAG_SPAN = 210
const COARSE_STEP = 0.04
const FINE_STEP = 0.007

function polar(radius: number, progress: number) {
  const radians =
    ((ANGLE_START + ANGLE_SWEEP * clamp(progress, 0, 1)) * Math.PI) / 180
  return [
    50 + radius * Math.cos(radians),
    50 + radius * Math.sin(radians),
  ] as const
}

function arc(from: number, to: number, radius: number) {
  const start = polar(radius, from)
  const end = polar(radius, to)
  const large = Math.abs(to - from) * ANGLE_SWEEP > 180 ? 1 : 0
  const sweep = to >= from ? 1 : 0
  return `M ${start[0]} ${start[1]} A ${radius} ${radius} 0 ${large} ${sweep} ${end[0]} ${end[1]}`
}

export type KnobProps = {
  variant?: 'band' | 'master'
  label: string
  value: number
  min: number
  max: number
  step: number
  unit?: string
  format: (value: number) => string
  defaultValue: number
  originAtDefault?: boolean
  disabled?: boolean
  disabledHint?: string
  toProgress?: (value: number) => number
  fromProgress?: (progress: number) => number
  onChange: (value: number) => void
}

/** Serum-ish metallic dial on MixStation graphite chrome. */
export function Knob({
  variant = 'band',
  label,
  value,
  min,
  max,
  step,
  unit,
  format,
  defaultValue,
  originAtDefault,
  disabled,
  disabledHint,
  toProgress,
  fromProgress,
  onChange,
}: KnobProps) {
  const id = useId().replace(/:/g, '')
  const bodyGradientId = `${id}-body`
  const capGradientId = `${id}-cap`
  const shadowId = `${id}-shadow`
  const dialRef = useRef<HTMLDivElement>(null)
  const gesture = useRef<{ y: number; progress: number } | null>(null)
  const [dragging, setDragging] = useState(false)
  const [editing, setEditing] = useState(false)
  const [draft, setDraft] = useState('')

  const asProgress = useCallback(
    (raw: number) =>
      clamp(toProgress ? toProgress(raw) : (raw - min) / (max - min), 0, 1),
    [max, min, toProgress],
  )
  const asValue = useCallback(
    (progress: number) => {
      const raw = fromProgress
        ? fromProgress(progress)
        : min + progress * (max - min)
      return clamp(Math.round(raw / step) * step, min, max)
    },
    [fromProgress, max, min, step],
  )

  const progress = asProgress(value)
  const defaultProgress = asProgress(defaultValue)
  const fillOrigin = originAtDefault ? defaultProgress : 0
  const pointerStart = polar(14, progress)
  const pointerEnd = polar(27, progress)

  useEffect(() => {
    const dial = dialRef.current
    if (!dial || disabled) return
    const onWheel = (event: globalThis.WheelEvent) => {
      event.preventDefault()
      const amount = event.shiftKey ? FINE_STEP : COARSE_STEP
      onChange(
        asValue(
          clamp(progress + (event.deltaY < 0 ? amount : -amount), 0, 1),
        ),
      )
    }
    dial.addEventListener('wheel', onWheel, { passive: false })
    return () => dial.removeEventListener('wheel', onWheel)
  }, [asValue, disabled, onChange, progress])

  const commitValue = useCallback(
    (next: number, animateSnap = false) => {
      onChange(next)
      if (animateSnap) snapKnobDial(dialRef.current)
    },
    [onChange],
  )

  const onPointerDown = (event: ReactPointerEvent<HTMLDivElement>) => {
    if (disabled || editing) return
    event.preventDefault()
    gesture.current = { y: event.clientY, progress }
    event.currentTarget.setPointerCapture(event.pointerId)
    setDragging(true)
  }

  const onPointerMove = (event: ReactPointerEvent<HTMLDivElement>) => {
    if (!gesture.current || disabled) return
    const delta = (gesture.current.y - event.clientY) / DRAG_SPAN
    onChange(
      asValue(
        clamp(
          gesture.current.progress + (event.shiftKey ? delta * 0.2 : delta),
          0,
          1,
        ),
      ),
    )
  }

  const endGesture = (event: ReactPointerEvent<HTMLDivElement>) => {
    gesture.current = null
    setDragging(false)
    if (event.currentTarget.hasPointerCapture(event.pointerId)) {
      event.currentTarget.releasePointerCapture(event.pointerId)
    }
  }

  const commitEdit = () => {
    const parsed = Number(draft.replace(/[^\d.+-]/g, ''))
    if (Number.isFinite(parsed)) commitValue(clamp(parsed, min, max), true)
    setEditing(false)
  }

  return (
    <div
      className={`knob is-${variant} flex min-w-0 flex-col items-center gap-1 ${
        dragging ? 'is-dragging' : ''
      } ${disabled ? 'pointer-events-none opacity-30' : ''}`}
      style={
        {
          '--control-accent':
            variant === 'master' ? 'var(--color-signal)' : 'var(--band)',
        } as Record<string, string>
      }
      title={disabled ? disabledHint : undefined}
    >
      <span className="label-cap">{label}</span>
      <div
        ref={dialRef}
        className="knob-dial h-14 w-14 cursor-ns-resize touch-none outline-none sm:h-16 sm:w-16"
        role="slider"
        tabIndex={disabled ? -1 : 0}
        aria-label={label}
        aria-valuemin={min}
        aria-valuemax={max}
        aria-valuenow={value}
        aria-valuetext={`${format(value)}${unit ? ` ${unit}` : ''}`}
        aria-disabled={disabled}
        title={
          disabled
            ? disabledHint
            : `${label} — drag vertically, Shift for fine, double-click to reset`
        }
        onPointerDown={onPointerDown}
        onPointerMove={onPointerMove}
        onPointerUp={endGesture}
        onPointerCancel={endGesture}
        onDoubleClick={() => !disabled && commitValue(defaultValue, true)}
        onContextMenu={(event) => {
          event.preventDefault()
          if (!disabled) commitValue(defaultValue, true)
        }}
        onKeyDown={(event) => {
          if (disabled) return
          const amount = event.shiftKey ? FINE_STEP : COARSE_STEP
          if (event.key === 'ArrowUp' || event.key === 'ArrowRight') {
            event.preventDefault()
            onChange(asValue(clamp(progress + amount, 0, 1)))
          }
          if (event.key === 'ArrowDown' || event.key === 'ArrowLeft') {
            event.preventDefault()
            onChange(asValue(clamp(progress - amount, 0, 1)))
          }
          if (event.key === 'Home') {
            event.preventDefault()
            commitValue(min, true)
          }
          if (event.key === 'End') {
            event.preventDefault()
            commitValue(max, true)
          }
        }}
      >
        <svg viewBox="0 0 100 100" className="block h-full w-full overflow-visible" aria-hidden="true">
          <defs>
            <linearGradient id={bodyGradientId} x1="0" x2="0" y1="0" y2="1">
              <stop offset="0" stopColor="#323b48" />
              <stop offset=".45" stopColor="#1a212c" />
              <stop offset="1" stopColor="#0a0d12" />
            </linearGradient>
            <radialGradient id={capGradientId} cx=".32" cy=".28" r=".8">
              <stop offset="0" stopColor="#3a4454" />
              <stop offset=".4" stopColor="#222a36" />
              <stop offset="1" stopColor="#10151c" />
            </radialGradient>
            <filter id={shadowId} x="-30%" y="-30%" width="160%" height="170%">
              <feDropShadow
                dx="0"
                dy="3"
                stdDeviation="3.5"
                floodColor="#000"
                floodOpacity=".55"
              />
            </filter>
          </defs>
          <circle className="knob-tick-ring" cx="50" cy="50" r="44" />
          <path className="knob-track" d={arc(0, 1, 42)} />
          <path className="knob-fill" d={arc(fillOrigin, progress, 42)} />
          <line
            className="knob-default"
            x1={polar(45, defaultProgress)[0]}
            y1={polar(45, defaultProgress)[1]}
            x2={polar(49, defaultProgress)[0]}
            y2={polar(49, defaultProgress)[1]}
          />
          <circle
            className="knob-body"
            cx="50"
            cy="50"
            r="33"
            fill={`url(#${bodyGradientId})`}
            filter={`url(#${shadowId})`}
          />
          <circle
            className="knob-cap"
            cx="50"
            cy="50"
            r="28"
            fill={`url(#${capGradientId})`}
          />
          <path className="knob-highlight" d="M32 37 A 22 22 0 0 1 67 31" />
          <line
            className="knob-pointer"
            x1={pointerStart[0]}
            y1={pointerStart[1]}
            x2={pointerEnd[0]}
            y2={pointerEnd[1]}
          />
          <circle className="knob-center" cx="50" cy="50" r="4.5" />
        </svg>
      </div>

      {editing ? (
        <input
          className="h-5 w-16 rounded border border-hairline-hi bg-well text-center text-[11px] text-ink outline-none"
          autoFocus
          value={draft}
          aria-label={`${label} value`}
          onChange={(event) => setDraft(event.target.value)}
          onBlur={commitEdit}
          onKeyDown={(event) => {
            if (event.key === 'Enter') commitEdit()
            if (event.key === 'Escape') setEditing(false)
          }}
        />
      ) : (
        <button
          type="button"
          className="readout flex min-h-5 min-w-14 cursor-text items-baseline justify-center gap-1 rounded px-1 hover:bg-white/5"
          disabled={disabled}
          title="Click to type a value"
          onClick={() => {
            setDraft(String(Number(value.toFixed(2))))
            setEditing(true)
          }}
        >
          <span>{format(value)}</span>
          {unit ? <i className="label-cap not-italic opacity-70">{unit}</i> : null}
        </button>
      )}
    </div>
  )
}

// crates/BuiltinAudioPlugins/crates/echospace/editorui/src/lib/Knob.svelte
<script lang="ts">
  import {
    clamp,
    format,
    fromNorm,
    toNorm,
    unitFor,
    type ParamSpec,
  } from '../params'

  type Props = {
    spec: ParamSpec
    value: number
    onchange: (value: number) => void
    /** Optional CSS size override, e.g. `5.5rem`. Defaults to `--knob-size`. */
    size?: string
    alert?: boolean
    disabled?: boolean
  }

  const {
    spec,
    value,
    onchange,
    size,
    alert = false,
    disabled = false,
  }: Props = $props()

  const norm = $derived(toNorm(spec, value))
  const uid = `k${Math.random().toString(36).slice(2, 9)}`

  let dragging = $state(false)
  let editing = $state(false)
  let draft = $state('')
  let inputEl: HTMLInputElement | undefined = $state()
  let dragStartY = 0
  let dragStartNorm = 0

  $effect(() => {
    if (editing) {
      inputEl?.focus()
      inputEl?.select()
    }
  })

  const TRAVEL_PX = 230

  function commit(nextNorm: number) {
    if (disabled) return
    onchange(fromNorm(spec, clamp(nextNorm, 0, 1)))
  }

  function onPointerDown(event: PointerEvent) {
    if (disabled || editing || event.button !== 0) return
    dragging = true
    dragStartY = event.clientY
    dragStartNorm = norm
    ;(event.currentTarget as HTMLElement).setPointerCapture(event.pointerId)
    event.preventDefault()
  }

  function onPointerMove(event: PointerEvent) {
    if (!dragging) return
    const travel = event.shiftKey ? TRAVEL_PX * 5 : TRAVEL_PX
    commit(dragStartNorm + (dragStartY - event.clientY) / travel)
  }

  function onPointerUp(event: PointerEvent) {
    if (!dragging) return
    dragging = false
    ;(event.currentTarget as HTMLElement).releasePointerCapture(event.pointerId)
  }

  function onWheel(event: WheelEvent) {
    if (disabled) return
    event.preventDefault()
    const step = event.shiftKey ? spec.step / 5 : spec.step
    onchange(
      clamp(value + (event.deltaY < 0 ? step : -step), spec.min, spec.max),
    )
  }

  function onKeyDown(event: KeyboardEvent) {
    if (disabled) return
    const step = event.shiftKey ? spec.step / 5 : spec.step
    switch (event.key) {
      case 'ArrowUp':
      case 'ArrowRight':
        onchange(clamp(value + step, spec.min, spec.max))
        break
      case 'ArrowDown':
      case 'ArrowLeft':
        onchange(clamp(value - step, spec.min, spec.max))
        break
      case 'PageUp':
        commit(norm + 0.1)
        break
      case 'PageDown':
        commit(norm - 0.1)
        break
      case 'Home':
        onchange(spec.default)
        break
      default:
        return
    }
    event.preventDefault()
  }

  function startEdit() {
    if (disabled) return
    draft = String(Number(value.toFixed(Math.max(spec.digits, 2))))
    editing = true
  }

  function commitEdit() {
    const parsed = Number(draft.replace(/[^\d.+-]/g, ''))
    if (Number.isFinite(parsed)) {
      onchange(clamp(parsed, spec.min, spec.max))
    }
    editing = false
  }

  const START_DEG = -225
  const SWEEP_DEG = 270
  const R = 41

  function polar(deg: number, radius: number) {
    const rad = (deg * Math.PI) / 180
    return { x: 50 + Math.cos(rad) * radius, y: 50 + Math.sin(rad) * radius }
  }

  function arc(fromNormValue: number, toNormValue: number, radius: number) {
    const a0 = START_DEG + SWEEP_DEG * fromNormValue
    const a1 = START_DEG + SWEEP_DEG * toNormValue
    const p0 = polar(a0, radius)
    const p1 = polar(a1, radius)
    const large = Math.abs(a1 - a0) > 180 ? 1 : 0
    const sweep = a1 >= a0 ? 1 : 0
    return `M ${p0.x.toFixed(2)} ${p0.y.toFixed(2)} A ${radius} ${radius} 0 ${large} ${sweep} ${p1.x.toFixed(2)} ${p1.y.toFixed(2)}`
  }

  const originNorm = $derived(
    spec.origin === undefined ? 0 : toNorm(spec, spec.origin),
  )
  const defaultNorm = $derived(toNorm(spec, spec.default))
  const pointer = $derived(polar(START_DEG + SWEEP_DEG * norm, R - 7))
  const inner = $derived(polar(START_DEG + SWEEP_DEG * norm, R - 24))
  const tip = $derived(polar(START_DEG + SWEEP_DEG * norm, R - 10))
  const defaultTick = $derived(polar(START_DEG + SWEEP_DEG * defaultNorm, 47))
  const defaultTickOuter = $derived(
    polar(START_DEG + SWEEP_DEG * defaultNorm, 51),
  )

  const ticks = [0, 0.25, 0.5, 0.75, 1].map((t) => {
    const deg = START_DEG + SWEEP_DEG * t
    return { a: polar(deg, 46.5), b: polar(deg, 49.5) }
  })
</script>

<div
  class="knob"
  class:disabled
  style={size ? `--knob-size: ${size}` : undefined}
>
  <div class="label">{spec.label}</div>
  <div
    class="dial"
    class:dragging
    class:alert
    role="slider"
    tabindex={disabled ? -1 : 0}
    aria-label={spec.label}
    aria-valuemin={spec.min}
    aria-valuemax={spec.max}
    aria-valuenow={value}
    aria-valuetext="{format(spec, value)} {unitFor(spec, value)}"
    aria-disabled={disabled}
    title="{spec.label} — drag vertically, Shift for fine, double-click to reset"
    onpointerdown={onPointerDown}
    onpointermove={onPointerMove}
    onpointerup={onPointerUp}
    onpointercancel={onPointerUp}
    onwheel={onWheel}
    onkeydown={onKeyDown}
    ondblclick={() => !disabled && onchange(spec.default)}
  >
    <svg viewBox="0 0 100 100" aria-hidden="true">
      <defs>
        <linearGradient id="{uid}-ring" x1="0" x2="0" y1="0" y2="1">
          <stop offset="0" stop-color="var(--knob-ring-hi)" />
          <stop offset="1" stop-color="var(--knob-ring-lo)" />
        </linearGradient>
        <linearGradient id="{uid}-body" x1="0" x2="0" y1="0" y2="1">
          <stop offset="0" stop-color="var(--knob-body-hi)" />
          <stop offset=".45" stop-color="var(--knob-body-mid)" />
          <stop offset="1" stop-color="var(--knob-body-lo)" />
        </linearGradient>
        <radialGradient id="{uid}-cap" cx=".32" cy=".24" r=".78">
          <stop offset="0" stop-color="var(--knob-cap-hi)" />
          <stop offset=".28" stop-color="var(--knob-cap-mid)" />
          <stop offset=".7" stop-color="var(--knob-cap-lo)" />
          <stop offset="1" stop-color="var(--knob-cap-edge)" />
        </radialGradient>
        <radialGradient id="{uid}-glow" cx=".5" cy=".5" r=".5">
          <stop offset="0" stop-color="var(--accent)" stop-opacity=".35" />
          <stop offset="1" stop-color="var(--accent)" stop-opacity="0" />
        </radialGradient>
        <filter id="{uid}-shadow" x="-35%" y="-35%" width="170%" height="180%">
          <feDropShadow
            dx="0"
            dy="3.5"
            stdDeviation="3.2"
            flood-color="#000"
            flood-opacity=".55"
          />
        </filter>
      </defs>

      {#each ticks as tick}
        <line class="tick" x1={tick.a.x} y1={tick.a.y} x2={tick.b.x} y2={tick.b.y} />
      {/each}

      <path class="track" d={arc(0, 1, R)} />
      {#if Math.abs(norm - originNorm) > 0.001}
        <path class="fill" d={arc(originNorm, norm, R)} />
      {/if}
      <line
        class="default"
        x1={defaultTick.x}
        y1={defaultTick.y}
        x2={defaultTickOuter.x}
        y2={defaultTickOuter.y}
      />

      <circle class="ring" cx="50" cy="50" r="35.5" fill="url(#{uid}-ring)" />
      <circle
        class="body"
        cx="50"
        cy="50"
        r="32.5"
        fill="url(#{uid}-body)"
        filter="url(#{uid}-shadow)"
      />
      <circle class="cap" cx="50" cy="50" r="27.5" fill="url(#{uid}-cap)" />
      <circle class="rim" cx="50" cy="50" r="27.5" />
      <path class="highlight" d="M30 39 A 22 22 0 0 1 67 31" />
      {#if dragging}
        <circle cx="50" cy="50" r="36" fill="url(#{uid}-glow)" />
      {/if}
      <line
        class="pointer"
        x1={inner.x}
        y1={inner.y}
        x2={pointer.x}
        y2={pointer.y}
      />
      <circle class="tip" cx={tip.x} cy={tip.y} r="2.1" />
    </svg>
  </div>

  {#if editing}
    <input
      class="input"
      bind:this={inputEl}
      bind:value={draft}
      aria-label="{spec.label} value"
      onblur={commitEdit}
      onkeydown={(event) => {
        if (event.key === 'Enter') commitEdit()
        if (event.key === 'Escape') editing = false
      }}
    />
  {:else}
    <button
      type="button"
      class="readout"
      {disabled}
      title="Click to type a value"
      onclick={startEdit}
    >
      <span class="value">{format(spec, value)}</span>
      <span class="unit">{unitFor(spec, value)}</span>
    </button>
  {/if}
</div>

<style>
  .knob {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 0.3rem;
    width: 100%;
    max-width: 5.4rem;
    min-width: 0;
  }

  .label {
    max-width: 100%;
    overflow: hidden;
    color: var(--text-muted);
    font-size: 0.68rem;
    font-weight: 600;
    letter-spacing: 0.01em;
    text-align: center;
    text-overflow: ellipsis;
    white-space: nowrap;
  }

  .dial {
    width: var(--knob-size);
    height: var(--knob-size);
    cursor: ns-resize;
    touch-action: none;
    outline: none;
    transition: transform 120ms ease;
  }

  .dial:hover {
    transform: scale(1.025);
  }

  .dial.dragging {
    transform: scale(1.035);
  }

  .knob.disabled .dial {
    cursor: default;
    opacity: 0.36;
    transform: none;
  }

  svg {
    display: block;
    width: 100%;
    height: 100%;
    overflow: visible;
  }

  .tick {
    stroke: rgba(255, 255, 255, 0.14);
    stroke-width: 1.25;
    stroke-linecap: round;
  }

  .track {
    fill: none;
    stroke: rgba(255, 255, 255, 0.08);
    stroke-width: 3.75;
    stroke-linecap: round;
  }

  .fill {
    fill: none;
    stroke: var(--accent);
    stroke-width: 3.75;
    stroke-linecap: round;
    filter: drop-shadow(
      0 0 2.5px color-mix(in srgb, var(--accent) 60%, transparent)
    );
  }

  .default {
    stroke: rgba(255, 255, 255, 0.28);
    stroke-width: 1.5;
    stroke-linecap: round;
  }

  .ring {
    stroke: rgba(255, 255, 255, 0.06);
    stroke-width: 0.75;
  }

  .body {
    stroke: rgba(255, 255, 255, 0.1);
    stroke-width: 1;
  }

  .cap {
    stroke: rgba(255, 255, 255, 0.035);
    stroke-width: 1;
  }

  .rim {
    fill: none;
    stroke: color-mix(in srgb, var(--accent) 14%, transparent);
    stroke-width: 1.1;
  }

  .highlight {
    fill: none;
    stroke: rgba(255, 255, 255, 0.2);
    stroke-width: 1.35;
    stroke-linecap: round;
  }

  .pointer {
    stroke: var(--knob-pointer);
    stroke-width: 2.4;
    stroke-linecap: round;
  }

  .tip {
    fill: var(--accent-bright);
    stroke: #fff;
    stroke-width: 0.6;
  }

  .dial.dragging .fill,
  .dial:hover .fill {
    stroke: var(--accent-bright);
  }

  .dial.dragging .body {
    stroke: color-mix(in srgb, var(--accent) 50%, transparent);
  }

  .dial.dragging .rim {
    stroke: color-mix(in srgb, var(--accent) 45%, transparent);
  }

  .dial.alert .fill {
    stroke: var(--warn);
    filter: none;
  }

  .dial.alert .tip {
    fill: var(--warn);
  }

  .readout {
    display: flex;
    align-items: baseline;
    justify-content: center;
    gap: 0.18rem;
    min-width: 4rem;
    min-height: 1.3rem;
    padding: 0.12rem 0.3rem;
    border-radius: var(--radius-sm);
    cursor: text;
  }

  .readout:hover {
    background: rgba(255, 255, 255, 0.05);
  }

  .value {
    color: var(--text);
    font-size: 0.8rem;
    font-weight: 600;
  }

  .unit {
    color: var(--text-faint);
    font-size: 0.62rem;
  }

  .input {
    width: 4.2rem;
    min-height: 1.3rem;
    padding: 0.12rem 0.3rem;
    border: 1px solid var(--border-strong);
    border-radius: var(--radius-sm);
    outline: none;
    background: var(--base);
    color: var(--text);
    font-size: 0.8rem;
    font-weight: 600;
    text-align: center;
    user-select: text;
  }
</style>
